### ISSUE TITLE
More sound formats

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#41]
We should only really support:
- WAVE (done)
- Opus
- Ogg
- FLAC

Anything else would be extraneous or subject to patent issues.

**Comment by Kyle873** [comment]
I believe we also talked about supporting tracker formats at some stage, but I'm not sure how much extra effort that will be and how well it can/will tie into the current audio system.

**Comment by marrub--** [comment]
No problems with that, it's fairly easy to support, but the music system will be rather complex and separate from sound support (even as far as not using the sound buffers system).

**Comment by DavidPH** [comment]
I think that list is good for the sound system. The music code can (and hopefully will) support other things like tracker formats, but I think the base sound system should only support plain audio formats. And for that, those should cover all of the reasonable needs. On the note of music, I wonder if music should be its own subsystem (`DGE::Music`?) that builds on `AL` (at the least in order to benefit from its format loading code for shared formats). I worry that otherwise we might end up conflating regular sounds and music, the latter of which is likely to have a very different sort of scripting API.

**Comment by marrub--** [comment]
Yeah, I was thinking that as well. Having music be a separate module would be good for organization since there will be a lot of orthogonal code between music and sound.

**Comment by Kyle873** [comment]
Agreed.

**Comment by marrub--** [comment]
OK, done with this. Going to open a separate issue for music.
