### ISSUE TITLE
Internationalization/Localization support

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#45]
This can probably be done with a string table like LANGUAGE or something.
It should be outside scripts and easily editable to work with any language to ease making translations of existing games.

**Comment by DavidPH** [comment]
Yes, having named strings to lookup seems like the right core. Just leaves the question of where is the lookup done. It needs to be easy/simple enough that it is practical to include its use early in a project's development without a big mass of boilerplate code. But I also want to avoid having to litter too many places internally with lookups.

We will most likely use `GDCC::Core::String` to store translated texts, so the natives for doing a lookup would be very simple. It might actually suffice for a majority of cases to just have said native, but I am not sure if there are reasonable use cases where that would be impractical.

**Comment by marrub--** [comment]
I haven't ever found it impractical in ZDoom. The %LS format parameter could also be implemented here, with the same semantics, heh.

**Comment by marrub--** [comment]
Okay, I have two solutions proposed for i18n:

- Use the GDCC string table and have translations be done with a native (`DGE_String_Translate` or something to that effect).
This is fast and works well but deciding where to store things is the bigger question.
- Let scripts handle translation, providing them with information on the system/user locale. (Not to say that the latter would exclude giving scripts this information, but it would be especially important this way.)

I like both ideas equally so it's really up to @Kyle873 and @DavidPH.

For l10n, `strftime` and other such calls need to respect system locale. This is more up to GDCC but this is also important to implement on DGE's side. This includes:
- `setlocale`
- `localeconv`
- `lconv`
- `LC_` macros
- `localtime`
- `strftime`
- `wcsftime`

We already support all UTF codepoints implicitly in all of the engine, **only** exception being #54. Text input is not implemented yet but we will need to account for #17 (which will require some SDL screwery).

**Comment by DavidPH** [comment]
Scripts need to be able to ask for the current locale, so I would say by extension it should always be an *option* for the user to write their own localization engine. However, as noted before, I think it is important to have a low cost of initial setup, so that users will be more inclined to use the feature from the beginning.

I would prefer to have translations defined in a file that the engine loads, rather than added dynamically at runtime. It would make it easier to optimize their storage as well as enabling third-party translations. Format would of course be NTS, and I would likely exploit that to build a hash table that just directly uses the file data. Syntax would probably be something like: `language { name text name text ... }`, repeated for whatever languages or using a different file for each language. Filename for this could be TEXTDEFS, in keeping with the current definitions theme.

API for reading translated text would probably comprise of a single native: `unsigned DGE_Text_Read(str name, char *buf, unsigned len);`. Would have the same sort of semantics as snprintf, so you could use a len of 0 to check the needed buffer size. (I know I suggested using GDCC::Core::String for storing translations before, but I have thought better of it.)

**Comment by marrub--** [comment]
Agree x10. I very much like this idea.

**Comment by Kyle873** [comment]
Sounds good to me.

**Comment by DavidPH** [comment]
What about language fallback? I expect to implement the TEXTDEFS loader in such a way that it at least *can* load all of the provided languages, so that should be the how of it, but how to choose what to fall back to?

I suppose the only other question is how to name the languages. I think there is at least one currently established convention, but I am woefully inexperienced in localization.

**Comment by marrub--** [comment]
[ISO 639-3 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-3_codes). Essentially, let the user use any 3 characters to represent a language name. Examples: `enu` U.S. English, `jpn` Japanese, `deu` German. All recorded human languages are present in ISO 639-3 and represents them all in 3 characters!

For fallback, should that be decided by scripts? ZDoom does it by having blocks marked "default", ie:
```ini
[enu default]
TEXT = "Fallback (U.S. English)";

[deu]
TEXT = "German";
```

**Comment by DavidPH** [comment]
And the fallback can be set from GAMEDEFS as a list of languages to try after considering the player's chosen locales. (Plural because of course the player should be allowed to select a secondary locale.)
