### ISSUE TITLE
GAMEDEFS format

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#55]
As discussed elsewhere, considering adding a new DGE_NTS format for defining engine defaults.
Here are the things I propose be added:

- Default (physical) window size
- Entry points to run on scripting init (maybe put this in CODEDEFS instead)
- Default engine tickrate
- Command-line options to add
- Texture/shader/font aliases to load

Could also maybe add arbitrary CODEDEFS/GAMEDEFS files from here, not sure on that.

**Comment by Kyle873** [comment]
If we have any adjustable audio/rendering options/features in the future that need custom init values beyond what the engine has set, they should go here too. Stuff like AA, default master volume, etc.

**Comment by marrub--** [comment]
Ah yeah, the engine probably should have a few built-in effects like FXAA. The master volume is also something that should be configurable, but I'd imagine scripts would do that instead because they might read a config file of some sort.

**Comment by DavidPH** [comment]
* Scripting entry points will be handled from CODEDEFS via loader callback registering.
* Allowing gamedata to apply command line options would be very bad. `ConsoleCommand` bad.
* Texture/shader/font aliases are a maybe, but we might need them to set up later.
* Not sure about AA, volume, etc. These will be user settings and I don't want to risk getting into some kind of arms race between GAMEDEFS settings and user settings.

Window size (and I would include virtual size) and tickrate are definitely good candidates, though. Being able to specify those early is good. I expect GAMEDEFS would be loaded immediately after processing command line options, by the way.

**Comment by marrub--** [comment]
Yeah, that's what I had in mind too. I was thinking command-line options would be useful but those are user options. Similarly, user options like global volume and effects should be done via scripts so as not to cause the FraggleScript effect (where it had one feature ACS didn't so you had to use it.)

Also useful would be setting the default window title.

**Comment by Kyle873** [comment]
I completely forgot about FraggleScript and the issues it caused regarding that. I suppose it would make more sense for all that stuff to just get set in the script entry point, and only relegate system-level stuff that needs immediate values/init to GAMEDEFS.
Also +1 for window title.

**Comment by marrub--** [comment]
Yep, basically anything that the engine does before CODEDEFS `main` is called needs to be put here. The list will likely grow as we add more features.

**Comment by DavidPH** [comment]
Having recently added the basic framework for defining GAMEDEFS values and some tentative conventions in defining them, I think it is time to discuss how to organize GAMEDEFS. Both from an external perspective (how we name and group them) and internally. Currently I have created `Window::Title`, `Window::Size`, and `Textdefs::Fallback` values. (Side note, but what notation should we use for nested GAMEDEFS names? I keep using `:: as a separator because that's natural to me, but I'd like to keep this consistent in documentation as much as possible. (There are no plans to have such a syntax in GAMEDEFS itself, leaving the option open to anyone adventurous/bored enough to make a GAMEDEFS compiler.))

The first question, and probably the most important: What are worthy names for top-level groups? We could, as above, just use sub-modules for top-level names. This would make sense if we do not expect to have many options in total. Alternatively, we could use module names, as in `Defs::TextdefsFallback` or module and sub-module names as in `Defs::Textdefs::Fallback`. These would both reduce namespace contention and the latter would map very nicely to the internal structure. (Which is probably reasonable for this sort of early/bootstrap config.) There is also the possibility of not bothering with groups at all and just having a small handful of options at the top-level. Or on the other extreme, using `DGE::Defs::Textdefs::Fallback`, though I would argue against this as it seems unlikely that GAMEDEFS would be used to extensively configure something other than DGE components. (But it would be useful if, for example, someone used DGE as a library instead of just scripting, to avoid namespace collisions from ongoing development.)

Next question: How to organize internally? If we have module-wide GAMEDEFS groups, where should that `Defs::GamedefsGroup` object be declared and defined? I think it would naturally go with the current Natives.hpp/cpp files we already have, so maybe just rename that to something more generic (Defs?). Additionally, where to put them in files? So far I've taken to putting them under the Options header, since they behave so much like options, rather than a separate GAMEDEFS header. (And even have started referring to them as a type of options in this very text.)

Lastly, though not a requirement before closing this issue: Do we have any other uses for GAMEDEFS at present? There is not a bounty of `Defs::Gamedefs` classes as there is for `GDCC::Option` classes, because it seemed likely that they would dwarf the actual usage of said classes. But there is no other philosophical opposition to such additions. But in case there is some serious deficiency in the core implementation, I raise the question now. (But most likely the core handling is fine and any additional `Defs::Gamedefs` classes can be added when they seem appropriate.)

**Comment by marrub--** [comment]
>Side note, but what notation should we use for nested GAMEDEFS names? I keep using `::` as a separator because that's natural to me, but I'd like to keep this consistent in documentation as much as possible.

Yes.

>The first question, and probably the most important: What are worthy names for top-level groups?

The second option, `Defs::Textdefs::Fallback` seems nicest to me.

>I think it would naturally go with the current Natives.hpp/cpp files we already have

Yes.

>so maybe just rename that to something more generic (Defs?)

Oh yes.

>So far I've taken to putting them under the Options header, since they behave so much like options, rather than a separate GAMEDEFS header. (And even have started referring to them as a type of options in this very text.)

Why contain it?
S'coo.

>Lastly, though not a requirement before closing this issue: Do we have any other uses for GAMEDEFS at present?

Not particularly as far as I can tell. We'll add them when we need them.
