### ISSUE TITLE
DGE_Object_Get/SetMember extensions

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#58]
Currently you can only get/set single-word types, and at that only some specific single-word types. The issue arises immediately as you need to add pointers or (VM) floats, doubles or long integers to your objects. Don't know if @DavidPH has a plan for this or not, so I'm making an issue for this.

**Comment by DavidPH** [comment]
This is something that really needs a solution on the GDCC side to make a sane solution on the engine side. What I would like to do is revisit my decision to do a split API for member access, and replace all of the accessors with one get and one set function, which takes a size in words to access. But this would require a way for GDCC to declare natives with a different name than their declared name.

Alternatively, I could use `__glyph` to give alternate names, or change the property member macros to use a function pointer cast.

The internal API will need to be reworked to handle OMs and EMs separately, as otherwise there would be unnecessary overhead to the former. Most likely, I will just move EM handling to the caller. Since there will only be two callers at this point, this would be fine. This will provide a side benefit of making bad OM access not fatal.

**Comment by marrub--** [comment]
クライムがおわりだ
